server:
  port: 9009
spring:
  application:
    name: tensquare-mq
  rabbitmq:
    host: 192.168.60.136
aliyun:
  sms:
    accessKeyId: LTAI90BXNlFeZ2wd
    accessKeySecret: nadvAMYdubHcG2Awm18mzcGgxHngZl